version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(deps): "
      include: "scope"
    target-branch: "dependabot-updates"
    open-pull-requests-limit: 1
