default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        exclude: ^helm-chart/renku-core/templates
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
        types: [python]
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        additional_dependencies: ["click==8.0.4"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        exclude: ^docs/
        args:
          - "--max-line-length=120"
          - "--show-source"
          - "--ignore=E121,E126,E203,E226,E231,W503,W504"
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - --ignore=D105,D107,D202,D203,D212,D213,D401,D406,D407,D410,D411,D413
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.990"
    hooks:
      - id: mypy
        args:
          - --no-strict-optional
          - --ignore-missing-imports
        additional_dependencies:
          - types-python-dateutil>=2.8.10
          - types-PyYAML<6.1.0,>=5.4
          - types-redis>=3.5.3,<4.1.0
          - types-requests<2.27.2,>=2.23.0
          - types-tabulate<0.8.10,>=0.7.7
          - attrs<21.5.0,>=21.4.0
          - filelock>=3.3.0,<3.6.1
  - repo: https://github.com/hadolint/hadolint
    rev: 'v2.10.0'
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
    - id: bandit
      args: [--configfile, pyproject.toml]
      types: [python]
      additional_dependencies: ["bandit[toml]"]
  - repo: local
    hooks:
    - id: poetry-check
      name: poetry check
      entry: poetry check
      language: system
      files: pyproject.toml
      pass_filenames: false
