repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            additional_dependencies: ["click==8.0.4"]
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            name: isort (python)
    - repo: https://github.com/pycqa/flake8
      rev: "6.0.0"
      hooks:
          - id: flake8
            exclude: ^docs/
            additional_dependencies:
            - Flake8-pyproject==1.2.2
    - repo: https://github.com/pycqa/pydocstyle
      rev: 4.0.1
      hooks:
          - id: pydocstyle
            args:
                - --ignore=D105,D107,D202,D203,D212,D213,D401,D406,D407,D410,D411,D413
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.8.0
      hooks:
          - id: shellcheck
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v0.990"
      hooks:
          - id: mypy
            args:
            - --no-strict-optional
            - --ignore-missing-imports
            additional_dependencies:
            - types-python-dateutil>=2.8.10
            - types-PyYAML<6.1.0,>=5.4
            - types-redis>=3.5.3,<4.1.0
            - types-requests<2.27.2,>=2.23.0
            - types-tabulate<0.8.10,>=0.7.7
            - attrs<21.5.0,>=21.4.0
            - filelock>=3.3.0,<3.6.1
    - repo: https://github.com/hadolint/hadolint
      rev: master
      hooks:
          - id: hadolint-docker
