apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "renku-core.fullname" . }}-nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;

    events {
      worker_connections 10000;
    }

    http {
      upstream v8 {
        server {{ include "renku-core.fullname" . }}-v8;
      }

      upstream v9 {
        server {{ include "renku-core.fullname" . }}-v9;
      }

      server {
        listen 80;

        server_name {{ include "renku-core.fullname" . }};

        sendfile on;
        tcp_nopush on;

        location /renku/deployments {
          root /;
          add_header Content-Type application/json;
          try_files /usr/share/nginx/html/deployments.json =404;
        }

        location /renku/8 {
          rewrite /renku/8/(.*) /renku/$1  break;
          proxy_set_header Host $host;
          proxy_pass http://v8;
        }

        location /renku/9 {
          rewrite /renku/9/(.*) /renku/$1  break;
          proxy_set_header Host $host;
          proxy_pass http://v9;
        }

        location /renku {
          proxy_set_header Host $host;
          proxy_pass http://v9;
        }
      }
    }
  deployments.json: |
    {
      "9": "{{ include "renku-core.fullname" . }}",
      "8": "{{ include "renku-core.fullname" . }}-v8"
    }
