apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "renku-core.fullname" . }}-metadata-versions
data:
  metadata-versions.json: |
    {
      "name": "renku-core",
      "versions": [
        {{- $printComma := false -}}
        {{- range $key, $version := .Values.versions }}
        {{- if $printComma }},{{ else }} {{- $printComma = true }} {{ end }}
        {
          "version": "{{ $version.image.tag }}",
          "data": {
            "metadata_version": "{{ $version.prefix }}"
          }
        }
        {{- end }}
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "renku-core.fullname" . }}-traefik
data:
  traefik-config.yaml: |
    http:
      routers:
        core:
          entryPoints:
            - web
          service: core
          rule: PathPrefix(`/api/renku`)
          middlewares:
            - auth-renku
            - cookiefilter
            - api
            {{- range $version := .Values.versions }}
            - {{ $version.name }}
            {{ end }}
      services:
        core:
          loadBalancer:
            servers:
              - url: http://localhost:8080
      middlewares:
        auth-renku:
          forwardAuth:
            address: "http://{{ .Values.gatewayAuth.serviceName }}/?auth=renku"
            trustForwardHeader: true
            authResponseHeaders: ["Authorization", "Renku-user-id", "Renku-user-fullname", "Renku-user-email"]
        api:
          stripPrefix:
            prefixes: ["/api"]
        no-cookies:
          headers:
            customRequestHeaders:
              Cookie: ""
        cookiefilter:
          plugin:
            cookiefilter:
              keepCookies:
                - stickyCoreIngressCookie
        {{- range $version := .Values.versions }}
        {{ $version.name }}:
          replacePathRegex:
            regex: "^/renku/{{ $version.prefix }}/(.*)"
            replacement: "/renku/$1"
        {{ end }}
