apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "renku-core.fullname" $ }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "renku-core.fullname" $ }}-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "renku-core.fullname" $ }}-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "renku-core.fullname" $ }}-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - chown
                - setgid
                - setuid
            runAsNonRoot: false
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: nginx-volume
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-volume
              readOnly: true
              mountPath: /usr/share/nginx/html/versions.json
              subPath: versions.json
      volumes:
        - name: nginx-volume
          configMap:
            name: {{ include "renku-core.fullname" . }}-nginx
