dependencies:
- name: redis
  version: 10.7.11
  repository: "https://charts.bitnami.com/bitnami"
- name: certificates
  version: 0.11.0-rc1
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"