# -*- coding: utf-8 -*-
#
# Copyright 2018 - Swiss Data Science Center (SDSC)
# A partnership between École Polytechnique Fédérale de Lausanne (EPFL) and
# Eidgenössische Technische Hochschule Zürich (ETHZ).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: renku
version: '0.2.0'
summary: A Python library for the Renku collaborative data science platform.
description: |
  A Python library for the Renku collaborative data science platform. It allows
  the user to create projects, manage datasets, and capture data provenance
  while performing analysis tasks.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  renku:
    command: bin/renku
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    plugs:
      - home
      - network
      - network-bind

parts:
  renku:
    plugin: python
    python-version: python3
    python-packages:
      - "git+https://github.com/SwissDataScienceCenter/python-future.git@fix-read-only#egg=future-0.16.0"
    source: .
    source-type: git
    stage-packages:
      - git
