name: Reformat code using black

on:
  pull_request:
    paths:
    - '**.py'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.RENKU_CI_TOKEN }}
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Format with black
      run: |
        python -m pip install --upgrade pip
        pip install black
        black .
    - name: Commit modified files
      run: |
        git config --local user.email "renku@datascience.ch"
        git config --local user.name "RenkuBot"
        git add -u
        git commit -m 'chore: automatically format with black' || true
        git push origin ${{ github.head_ref }}
