name: Check PR documentation label

on
  pull_request:
    types: ['labeled', 'synchronize']

jobs:
  check_pr_milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: cchantep/probot-pr-status-label@ghaction-1.0.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
