name: Check PR documentation label

on:
  pull_request:
    types: ['labeled', 'synchronize']

jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check documentation is added
        run: echo '${{ toJson(github.event.pull_request.labels) }}' | grep -zqv 'documentation:pending'
