name: "Combine Dependabot PRs"
on:
  workflow_dispatch:

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
          token: "${{ secrets.RENKUBOT_GITHUB_TOKEN }}"
      - name: Setup local branch and merge tool
        run: |
          git branch --track dependabot-updates origin/dependabot-updates
          echo "poetry.lock merge=ours" >> .git/info/attributes
          git config merge.ours.driver true
      - uses: github/combine-prs@main
        with:
          branch_prefix: "dependabot"
          ci_required: false
          ignore_label: "nocombine"
          open_pr: true
          github_token: "${{ secrets.RENKUBOT_GITHUB_TOKEN }}"
          pr_title: "chore: combined dependency update"
