name: CI-integration-tests

on:
  push:
    branches:
      - master

jobs:
  test-linux-integration:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      env:
        IT_OAUTH_GIT_TOKEN: ${{ secrets.IT_OAUTH_GIT_TOKEN }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[nodocs]
        git config --global --add user.name "Renku @ SDSC"
        git config --global --add user.email "renku@datascience.ch"
    - name: Test with pytest
      run: pytest -m integration -v

  test-macos-integration:
    runs-on: macos-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      env:
        IT_OAUTH_GIT_TOKEN: ${{ secrets.IT_OAUTH_GIT_TOKEN }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        brew update
        brew install git-lfs shellcheck node || brew link --overwrite node
        python -m pip install --upgrade pip
        python -m pip install -e .[all]
        git config --global --add user.name "Renku @ SDSC"
        git config --global --add user.email "renku@datascience.ch"
    - name: Test with pytest
      run: pytest -m integration -v
