name: Publish SHACL shape for current version

on:
  push:
    branches:
      - master
    paths:
      - 'renku/data/shacl_shape.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/actions/install-linux
        with:
          python-version: "3.10"
      - name: Publish shape
        run: |
          git clone https://${{secrets.RENKUBOT_GITHUB_TOKEN}}@github.com/SwissDataScienceCenter/renku-ontology.git shacl_publish
          cd shacl_publish
          mkdir $(renku --version)
          cp ../renku/data/shacl_shape.json ./$(renku --version)/
          git config --local user.email "renku@datascience.ch"
          git config --local user.name "RenkuBot"
          git add $(renku --version)/shacl_shape.json
          git commit -m "Publish SHACL shape for $(renku --version)"
          git push
