name: Publish SHACL shape for current version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[all]
    - name: Publish shape
      run: |
        git clone https://${{secrets.SHACL_ACCESS_TOKEN}}@github.com/SwissDataScienceCenter/renku-ontology.git shacl_publish
        cd shacl_publish
        mkdir $(renku --version)
        cp ../renku/data/shacl_shape.json ./$(renku --version)/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add $(renku --version)/shacl_shape.json
        git commit -m "Publish SHACL shape for $(renku --version)"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.SHACL_ACCESS_TOKEN}}
        repository: SwissDataScienceCenter/renku-ontology
        directory: shacl_publish
