name: Integration Test when Publishing to External Data Warehouses

on:
  push:
    branches:
      - master
      - develop
    paths:
      - renku/core/commands/providers/*.py

jobs:
  test-linux-integration-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/actions/install-linux
        with:
          python-version: "3.10"
      - name: Test with pytest
        env:
          DATAVERSE_ACCESS_TOKEN: ${{ secrets.DATAVERSE_ACCESS_TOKEN }}
          IT_OAUTH_GIT_TOKEN: ${{ secrets.IT_OAUTH_GIT_TOKEN }}
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
          OLOS_ACCESS_TOKEN: ${{ secrets.OLOS_ACCESS_TOKEN }}
        run: pytest -m publish -v
